export const GET_ALL_BOOKS = "GET_ALL_BOOKS";
export const GET_DETAIL_BOOKS = "GET_DETAIL_BOOKS";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";
export const FILTER_BY_AUTOR = "FILTER_BY_AUTOR";
export const SEARCH_NAME_BOOK = "SEARCH_NAME_BOOK";
